## site information
# name and siteurl
name: {en: Chenlin Wang, cn: 王琛林}
title: Tech
email: chenlin.wang520@gmail.com
url: http://chenlin.me/en
# Time Zone
timezone: Asia/Hong_Kong
# Encoding
encoding: utf-8

## Conversion
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:year/:month/:title/
author: Chenlin Wang
highlighter: pygments
